### ISSUE TITLE
AWS SES email tracking not work

### ISSUE THREAD

**Issue by syaiful9507** [mettle/sendportal#210]
i have completely setup the email tracking on aws ses like documentation on https://sendportal.io/docs/v2/email-services/aws but email tracking is not work. 
if i use php artisan queue:work --queue=sendportal-webhook-process not showing something else
how to solve it ,

**Comment by umerghori786** [comment]
is your issue is solved or not...facing same issue

**Comment by syaiful9507** [comment]
This problem is not solved. If anyone have solution i think help us.

**Comment by umerghori786** [comment]
Thanks for answer! can you tell me is your track option and track clicks are enable or not ? [
![image](https://user-images.githubusercontent.com/65702036/160435689-3f81f5dc-0c81-4589-9f2f-d6756144b132.png)
](url) in my case it is disable

**Comment by umerghori786** [comment]
i create topic subscription but i dont know this also disable in my case when i create campain

**Comment by syaiful9507** [comment]
> Thanks for answer! can you tell me is your track option and track clicks are enable or not ? [ ![image](https://user-images.githubusercontent.com/65702036/160435689-3f81f5dc-0c81-4589-9f2f-d6756144b132.png) ](url) in my case it is disable



> Thanks for answer! can you tell me is your track option and track clicks are enable or not ? [ ![image](https://user-images.githubusercontent.com/65702036/160435689-3f81f5dc-0c81-4589-9f2f-d6756144b132.png) ](url) in my case it is disable

yes. my track options and open track is enable .
